phrase:
  access_token: c85e7e4996c0a7b28afcff9555a03fe4906df162bfb0406381d8d027a0fa2370
  project_id: 8c7c8be729dc8334cd7b9229d1d97c2e
  push:
    sources:

    - file: src/locales/admin/en/admin.json
      params:
        file_format: simple_json
        locale_id: 183a41c3b5a83e3f3fdec0436881aca6
        update_translations: true
        tags: admin

    - file: src/locales/admin/en/components/addDepartment.json
      params:
        file_format: simple_json
        locale_id: 183a41c3b5a83e3f3fdec0436881aca6
        update_translations: true
        tags: addDepartment

    - file: src/locales/admin/en/components/api.json
      params:
        file_format: simple_json
        locale_id: 183a41c3b5a83e3f3fdec0436881aca6
        update_translations: true
        tags: api

    - file: src/locales/admin/en/components/companyDetails.json
      params:
        file_format: simple_json
        locale_id: 183a41c3b5a83e3f3fdec0436881aca6
        update_translations: true
        tags: companyDetails

    - file: src/locales/admin/en/components/department.json
      params:
        file_format: simple_json
        locale_id: 183a41c3b5a83e3f3fdec0436881aca6
        update_translations: true
        tags: department

    - file: src/locales/admin/en/components/editDepartment.json
      params:
        file_format: simple_json
        locale_id: 183a41c3b5a83e3f3fdec0436881aca6
        update_translations: true
        tags: editDepartment

    - file: src/locales/admin/en/components/preferences.json
      params:
        file_format: simple_json
        locale_id: 183a41c3b5a83e3f3fdec0436881aca6
        update_translations: true
        tags: preferences

    - file: src/locales/admin/en/components/users/editUser.json
      params:
        file_format: simple_json
        locale_id: 183a41c3b5a83e3f3fdec0436881aca6
        update_translations: true
        tags: editUser

    - file: src/locales/admin/en/components/users/listUser.json
      params:
        file_format: simple_json
        locale_id: 183a41c3b5a83e3f3fdec0436881aca6
        update_translations: true
        tags: listUser

    - file: src/locales/admin/en/components/users/invite_users/EndComponent.json
      params:
        file_format: simple_json
        locale_id: 183a41c3b5a83e3f3fdec0436881aca6
        update_translations: true
        tags: EndComponent

    - file: src/locales/admin/en/components/users/invite_users/inviteComponent.json
      params:
        file_format: simple_json
        locale_id: 183a41c3b5a83e3f3fdec0436881aca6
        update_translations: true
        tags: inviteComponent

    - file: src/locales/admin/en/components/users/invite_users/linkComponent.json
      params:
        file_format: simple_json
        locale_id: 183a41c3b5a83e3f3fdec0436881aca6
        update_translations: true
        tags: linkComponent

    - file: src/locales/analytics/en/analytics.json
      params:
        file_format: simple_json
        locale_id: 183a41c3b5a83e3f3fdec0436881aca6
        update_translations: true
        tags: analytics
  
    - file: src/locales/auth/en/components/signIn.json
      params:
        file_format: simple_json
        locale_id: 183a41c3b5a83e3f3fdec0436881aca6
        update_translations: true
        tags: signIn

    - file: src/locales/auth/en/components/byPassLogin.json
      params:
        file_format: simple_json
        locale_id: 183a41c3b5a83e3f3fdec0436881aca6
        update_translations: true
        tags: byPassLogin

    - file: src/locales/auth/en/components/forgetPassword.json
      params:
        file_format: simple_json
        locale_id: 183a41c3b5a83e3f3fdec0436881aca6
        update_translations: true
        tags: forgetPassword

    - file: src/locales/auth/en/components/loadingComponent.json
      params:
        file_format: simple_json
        locale_id: 183a41c3b5a83e3f3fdec0436881aca6
        update_translations: true
        tags: loadingComponent

    - file: src/locales/auth/en/components/resetPassword.json
      params:
        file_format: simple_json
        locale_id: 183a41c3b5a83e3f3fdec0436881aca6
        update_translations: true
        tags: resetPassword

    - file: src/locales/auth/en/components/signUp.json
      params:
        file_format: simple_json
        locale_id: 183a41c3b5a83e3f3fdec0436881aca6
        update_translations: true
        tags: signUp

    - file: src/locales/auth/en/components/signUpDetails.json
      params:
        file_format: simple_json
        locale_id: 183a41c3b5a83e3f3fdec0436881aca6
        update_translations: true
        tags: signUpDetails

    - file: src/locales/auth/en/components/signUpVerification.json
      params:
        file_format: simple_json
        locale_id: 183a41c3b5a83e3f3fdec0436881aca6
        update_translations: true
        tags: signUpVerification

    - file: src/locales/auth/en/components/successComponent.json
      params:
        file_format: simple_json
        locale_id: 183a41c3b5a83e3f3fdec0436881aca6
        update_translations: true
        tags: successComponent
  
    - file: src/locales/external/en/components/completeComponent.json
      params:
        file_format: simple_json
        locale_id: 183a41c3b5a83e3f3fdec0436881aca6
        update_translations: true
        tags: completeComponent

    - file: src/locales/external/en/components/emailValidation.json
      params:
        file_format: simple_json
        locale_id: 183a41c3b5a83e3f3fdec0436881aca6
        update_translations: true
        tags: emailValidation

    - file: src/locales/external/en/components/onboardingIngComponent.json
      params:
        file_format: simple_json
        locale_id: 183a41c3b5a83e3f3fdec0436881aca6
        update_translations: true
        tags: onboardingIngComponent

    - file: src/locales/external/en/components/passworValidationComponent.json
      params:
        file_format: simple_json
        locale_id: 183a41c3b5a83e3f3fdec0436881aca6
        update_translations: true
        tags: passworValidationComponent

    - file: src/locales/external/en/count.json
      params:
        file_format: simple_json
        locale_id: 183a41c3b5a83e3f3fdec0436881aca6
        update_translations: true
        tags: count

    - file: src/locales/headers/en/MainHeader.json
      params:
        file_format: simple_json
        locale_id: 183a41c3b5a83e3f3fdec0436881aca6
        update_translations: true
        tags: MainHeader

  pull:
    targets:

    - file: src/locales/admin/fr/admin.json
      params:
        file_format: simple_json
        locale_id: e8f9427353191aa2135b0f713a303589
        tags: admin

    - file: src/locales/admin/fr/components/addDepartment.json
      params:
        file_format: simple_json
        locale_id: e8f9427353191aa2135b0f713a303589
        tags: addDepartment

    - file: src/locales/admin/fr/components/api.json
      params:
        file_format: simple_json
        locale_id: e8f9427353191aa2135b0f713a303589
        tags: api

    - file: src/locales/admin/en/components/companyDetails.json
      params:
        file_format: simple_json
        locale_id: e8f9427353191aa2135b0f713a303589
        tags: companyDetails

    - file: src/locales/admin/fr/components/department.json
      params:
        file_format: simple_json
        locale_id: e8f9427353191aa2135b0f713a303589
        tags: department

    - file: src/locales/admin/fr/components/editDepartment.json
      params:
        file_format: simple_json
        locale_id: e8f9427353191aa2135b0f713a303589
        tags: editDepartment

    - file: src/locales/admin/fr/components/preferences.json
      params:
        file_format: simple_json
        locale_id: e8f9427353191aa2135b0f713a303589
        tags: preferences

    - file: src/locales/admin/fr/components/users/editUser.json
      params:
        file_format: simple_json
        locale_id: e8f9427353191aa2135b0f713a303589
        tags: editUser

    - file: src/locales/admin/fr/components/users/listUser.json
      params:
        file_format: simple_json
        locale_id: e8f9427353191aa2135b0f713a303589
        tags: listUser

    - file: src/locales/admin/fr/components/users/invite_users/EndComponent.json
      params:
        file_format: simple_json
        locale_id: e8f9427353191aa2135b0f713a303589
        tags: EndComponent

    - file: src/locales/admin/fr/components/users/invite_users/inviteComponent.json
      params:
        file_format: simple_json
        locale_id: e8f9427353191aa2135b0f713a303589
        tags: inviteComponent

    - file: src/locales/admin/fr/components/users/invite_users/linkComponent.json
      params:
        file_format: simple_json
        locale_id: e8f9427353191aa2135b0f713a303589
        tags: linkComponent

    - file: src/locales/analytics/fr/analytics.json
      params:
        file_format: simple_json
        locale_id: e8f9427353191aa2135b0f713a303589
        tags: analytics
  
    - file: src/locales/auth/fr/components/signIn.json
      params:
        file_format: simple_json
        locale_id: e8f9427353191aa2135b0f713a303589
        tags: signIn

    - file: src/locales/auth/fr/components/byPassLogin.json
      params:
        file_format: simple_json
        locale_id: e8f9427353191aa2135b0f713a303589
        tags: byPassLogin

    - file: src/locales/auth/fr/components/forgetPassword.json
      params:
        file_format: simple_json
        locale_id: e8f9427353191aa2135b0f713a303589
        tags: forgetPassword

    - file: src/locales/auth/fr/components/loadingComponent.json
      params:
        file_format: simple_json
        locale_id: e8f9427353191aa2135b0f713a303589
        tags: loadingComponent

    - file: src/locales/auth/fr/components/resetPassword.json
      params:
        file_format: simple_json
        locale_id: e8f9427353191aa2135b0f713a303589
        tags: resetPassword

    - file: src/locales/auth/fr/components/signUp.json
      params:
        file_format: simple_json
        locale_id: e8f9427353191aa2135b0f713a303589
        tags: signUp

    - file: src/locales/auth/fr/components/signUpDetails.json
      params:
        file_format: simple_json
        locale_id: e8f9427353191aa2135b0f713a303589
        tags: signUpDetails

    - file: src/locales/auth/fr/components/signUpVerification.json
      params:
        file_format: simple_json
        locale_id: e8f9427353191aa2135b0f713a303589
        tags: signUpVerification

    - file: src/locales/auth/fr/components/successComponent.json
      params:
        file_format: simple_json
        locale_id: e8f9427353191aa2135b0f713a303589
        tags: successComponent
  
    - file: src/locales/external/fr/components/completeComponent.json
      params:
        file_format: simple_json
        locale_id: e8f9427353191aa2135b0f713a303589
        tags: completeComponent

    - file: src/locales/external/fr/components/emailValidation.json
      params:
        file_format: simple_json
        locale_id: e8f9427353191aa2135b0f713a303589
        tags: emailValidation

    - file: src/locales/external/fr/components/onboardingIngComponent.json
      params:
        file_format: simple_json
        locale_id: e8f9427353191aa2135b0f713a303589
        tags: onboardingIngComponent

    - file: src/locales/external/fr/components/passworValidationComponent.json
      params:
        file_format: simple_json
        locale_id: e8f9427353191aa2135b0f713a303589
        tags: passworValidationComponent

    - file: src/locales/external/fr/count.json
      params:
        file_format: simple_json
        locale_id: e8f9427353191aa2135b0f713a303589
        tags: count

    - file: src/locales/headers/fr/MainHeader.json
      params:
        file_format: simple_json
        locale_id: e8f9427353191aa2135b0f713a303589
        tags: MainHeader
