phrase:
  access_token: c85e7e4996c0a7b28afcff9555a03fe4906df162bfb0406381d8d027a0fa2370
  project_id: 8c7c8be729dc8334cd7b9229d1d97c2e
  push:
    sources:
    - file: src/locales/auth/en/components/signIn.json
      params:
        file_format: simple_json
        locale_id: 183a41c3b5a83e3f3fdec0436881aca6
        update_translations: true
        tags: signIn

    - file: src/locales/external/en/components/completeComponent.json
      params:
        file_format: simple_json
        locale_id: 183a41c3b5a83e3f3fdec0436881aca6
        update_translations: true
        tags: completeComponent

    - file: src/locales/external/en/components/emailValidation.json
      params:
        file_format: simple_json
        locale_id: 183a41c3b5a83e3f3fdec0436881aca6
        update_translations: true
        tags: emailValidation

    - file: src/locales/external/en/components/onboardingIngComponent.json
      params:
        file_format: simple_json
        locale_id: 183a41c3b5a83e3f3fdec0436881aca6
        update_translations: true
        tags: onboardingIngComponent

    - file: src/locales/external/en/components/passworValidationComponent.json
      params:
        file_format: simple_json
        locale_id: 183a41c3b5a83e3f3fdec0436881aca6
        update_translations: true
        tags: passworValidationComponent

    - file: src/locales/external/en/count.json
      params:
        file_format: simple_json
        locale_id: 183a41c3b5a83e3f3fdec0436881aca6
        update_translations: true
        tags: count

    - file: src/locales/headers/en/MainHeader.json
      params:
        file_format: simple_json
        locale_id: 183a41c3b5a83e3f3fdec0436881aca6
        update_translations: true
        tags: MainHeader

  pull:
    targets:
    - file: src/locales/auth/fr/components/signIn.json
      params:
        file_format: simple_json
        locale_id: e8f9427353191aa2135b0f713a303589
        tags: signIn

    - file: src/locales/external/fr/components/completeComponent.json
      params:
        file_format: simple_json
        locale_id: e8f9427353191aa2135b0f713a303589
        tags: completeComponent

    - file: src/locales/external/fr/components/emailValidation.json
      params:
        file_format: simple_json
        locale_id: e8f9427353191aa2135b0f713a303589
        tags: emailValidation

    - file: src/locales/external/fr/components/onboardingIngComponent.json
      params:
        file_format: simple_json
        locale_id: e8f9427353191aa2135b0f713a303589
        tags: onboardingIngComponent

    - file: src/locales/external/fr/components/passworValidationComponent.json
      params:
        file_format: simple_json
        locale_id: e8f9427353191aa2135b0f713a303589
        tags: passworValidationComponent

    - file: src/locales/external/fr/count.json
      params:
        file_format: simple_json
        locale_id: e8f9427353191aa2135b0f713a303589
        tags: count

    - file: src/locales/headers/fr/MainHeader.json
      params:
        file_format: simple_json
        locale_id: e8f9427353191aa2135b0f713a303589
        tags: MainHeader
