import actions from './actions';
import getters from './getters';
import mutations from './mutations';

export default {
  namespaced: true,
  state() {
    return {
      active_package_class: '',
      active_vendor_name: '',
      active_vendor_details: {},
      schedule_end_time: '',
      active_order_option: '',
      price_request_object: {},
      max_destinations: 24,
      order_path: [],
      location_names: [],
      saved_cards: [],
      schedule_time: '',
      order_notes: '',
      extra_destinations: 0,
      pickup_filled: false,
      payment_method: '',
      stripe_user_id: '',
      carrier_type_id: '',
      return_status: false,
      max_temperature: 4,
      customer_min_amount: '',
      delivery_item: '',
      load_weight: '',
      load_units: 'tonnes',
      additional_loader: '',
      no_of_loaders: 0,
      order_state: 1,
      extended_options: false,
      pair_rider_status: false,
      pair_serial_number: '',
      pair_rider_phone: '',
      country_code: '',
      default_currency: '',
      test_specs: '',
      load_weight_val: 0,
      load_weight_status: false,
      product_categories: [],
      product_phase: 1,
      product_id: 1,
      vehicle_plate: '',
      pair_rider_state: false,
      pair_error_msg: '',
      instruction_notes: [],
      inter_county_order_details: {
        pickup_delivery_status: false,
        pickup_pricing_uuid: '',
        destination_delivery_status: false,
        destination_delivery_mode: '',
        package_type: '',
        approximate_weight: '',
        recipient_info: {},
        pickup_waypoint_instructions: [],
      },
    };
  },
  actions,
  getters,
  mutations,
};
